extends:
  - next/core-web-vitals

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

rules:
  no-console: warn
  no-unused-vars: warn
  react/prop-types: off
  react/react-in-jsx-scope: off

env:
  browser: true
  node: true
  es6: true