name: Lint Code Base

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          CSS_FILE_NAME: stylelint.config.js
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_CSS: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          FILTER_REGEX_INCLUDE: .*\.(js|jsx|ts|tsx|css|json|yml|yaml|md)$
      
      - name: Run ESLint with ReviewDog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '--ext .js,.jsx,.ts,.tsx .'
          fail_on_error: false
      
      - name: Run Stylelint with ReviewDog
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          stylelint_config: .github/linters/stylelint.config.js
          stylelint_input: '**/*.css'
          fail_on_error: false